apiVersion: v1
kind: ReplicationController
metadata:
 name: model-demo
 namespace: app-ehm
spec:
 replicas: 1
 selector:
   app: model-demo
 template:
   metadata:
     labels:
       app: model-demo
   spec:
     containers:
     - name: model-demo
       image: model-demo:v0.0.2

---
apiVersion: v1
kind: Service
metadata:
 name: model-demo
spec:
 type: NodePort
 ports:
 - port: 80
   nodePort: 30122 
 selector:
   app: model-demo
